# Generated by Django 4.1 on 2024-11-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='archivos/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lexema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lexema', models.CharField(max_length=100)),
                ('token', models.CharField(choices=[('saludo', 'Saludo'), ('despedida', 'Despedida'), ('identificacion_cliente', 'Identificación Cliente'), ('bueno', 'Bueno'), ('amable', 'Amable'), ('problema', 'Problema'), ('mal', 'Mal'), ('excelente', 'Excelente'), ('fatal', 'Fatal')], max_length=50)),
                ('ponderacion', models.IntegerField(default=0)),
            ],
        ),
    ]
